Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-10"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "windows-vagrant-lab-5"
    vb.memory = 4196
    vb.cpus = 2
  end

  config.vm.network "forwarded_port", guest: 5005, host: 5005
  config.vm.network "forwarded_port", guest: 5006, host: 5006

  config.vm.provision "shell", path: "../Scripts/installTools.bat"

  #config.vm.provision "shell", inline: "dotnet nuget add source --name mynuget http://192.168.56.1:5000/v3/index.json" # 192.168.31.189
  #config.vm.provision "shell", inline: "dotnet add package ORozdobudko --version 1.0.0"

  config.vm.provision "shell", path: "../Scripts/loadApp.bat"
end
