Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/focal64"
    config.vm.provider "virtualbox"
    
    config.vm.provision "shell", inline: "sudo apt-get install unzip"
    config.vm.provision "shell", inline: "wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb"
    config.vm.provision "shell", inline: "sudo dpkg -i packages-microsoft-prod.deb"
    config.vm.provision "shell", inline: "rm packages-microsoft-prod.deb"
    config.vm.provision "shell", inline: "sudo apt-get update && sudo apt-get install -y dotnet-sdk-6.0"
    config.vm.provision "shell", inline: "sudo apt update && sudo apt upgrade -y"
    
    config.vm.provision "shell", inline: "curl -L -o /tmp/cross_app.zip https://github.com/Alex-knu/Cross_platform/archive/refs/heads/master.zip"
    
    config.vm.provision "shell", inline: "dotnet nuget add source --name mynuget http://192.168.56.1:5000/v3/index.json" # 192.168.31.189
    config.vm.provision "shell", inline: "dotnet add package ORozdobudko --version 1.0.0"
    
    config.vm.provision "shell", inline: "sudo mkdir -p /var/cross_app"
    config.vm.provision "shell", inline: "sudo rm -rf /var/cross_app/src"
    config.vm.provision "shell", inline: "sudo mkdir -p /var/cross_app/src"
    config.vm.provision "shell", inline: "sudo chmod +x /var/cross_app/src"
    config.vm.provision "shell", inline: "sudo unzip /tmp/cross_app.zip -d /var/cross_app/src"
    
    config.vm.provision "shell", inline: "sudo rm -rf /var/cross_app/app"
    config.vm.provision "shell", inline: "dotnet build /var/cross_app/src/Cross_platform-master -c Release -o /var/cross_app/app"
    config.vm.provision "shell", inline: "dotnet publish /var/cross_app/src/Cross_platform-master -c Release -o /var/cross_app/app"
end
